version: '3.7'

networks:
  my-networks:
    driver: bridge
services:
  mongo:
    container_name: mongo
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - '27017:27017'
    command: mongod --port 27017
    volumes: 
      - mongodb-cache:/data
    networks:
      - my-networks
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis-cache:/data
  grpc-command:
    container_name: grpc-command
    restart: always
    build:
      context: ./grpc-command
      dockerfile: Dockerfile
      target: grpc-command
    networks:
      - my-networks
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - '50051'
    links:
      - mongo
    ports:
      - '50051:50051'
    depends_on:
      - mongo
    command: npm run start
volumes:
  redis-cache:
    driver: local
  mongodb-cache:
    driver: local