version: '3.7'

services:
  mongo:
    container_name: mongo
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - '27017:27017'
    command: mongod --port 27017
    volumes: 
      - mongodb-cache:/data
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis-cache:/data
  grpc-command:
    container_name: grpc-command
    restart: always
    build:
      context: ./grpc-command
      dockerfile: Dockerfile
      target: grpc-command
    environment:
      - PORT=50051
      - HOST=grpc-command
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - '50051'
    links:
      - mongo
    ports:
      - '50051:50051'
    depends_on:
      - mongo
    command: npm run start
  api:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api
    environment:
      - PORT=3000
      - GRPC_COMMAND_HOST=grpc-command
    expose:
      - '3000'
    links:
      - mongo
      - grpc-command
    ports:
      - '3000:3000'
    depends_on:
       - mongo
       - grpc-command
    command: npm run start
volumes:
  redis-cache:
    driver: local
  mongodb-cache:
    driver: local